version: "3"
services:
    frontend:
        build:
            context: ./client
        ports:
            - "${CLIENT_PORT}:${CLIENT_PORT}"
        container_name: max_web
        stdin_open: true
        volumes:
            - ./client:/usr/src/app/client
            - /usr/src/app/client/node_modules
        # image: akinney/max_web
    backend:
        build:
            context: ./server
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        container_name: max_server
        volumes:
            - ./server:/usr/src/app/server
            - /usr/src/app/server/node_modules
        # image: akinney/max_server
    storybook:
        container_name: max_stories
        build:
            context: ./client
            # dockerfile: Dockerfile
        # image: akinney/max_stories
        command: npm run storybook
        init: true
        ports:
            - "${STORIES_PORT}:${STORIES_PORT}"
        # volumes:
        #     - ./client:/usr/src/app


